/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInquiry = IDL.Record({
  'vehicleType' : IDL.Text,
  'destination' : IDL.Text,
  'numPassengers' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'travelDate' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getTotalInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInquiry = IDL.Record({
    'vehicleType' : IDL.Text,
    'destination' : IDL.Text,
    'numPassengers' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'travelDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getTotalInquiriesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };